name: Lint

on:
  push:
    branches:
      - develop
      - release/*
  pull_request:

jobs:
  ktlint:
    name: ktlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Run lint script
        run: ./scripts/lint.sh
